dtb-$(CONFIG_ARCH_ROCKCHIP) += smarcore-rk3399-starterkit-linux.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += smarcore-rk3399-starterkit-linux-dp.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += smarcore-rk3399-starterkit-linux-hdmi4k.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += smarcore-rk3399-starterkit-linux-dp4k.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
