dtb-$(CONFIG_ARCH_ROCKCHIP) += px30-core-evb2-linux.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += px30-core-evb2-linux-dual.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += px30-core-ctouch2-linux.dtb

always		:= $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb
